//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Reactive {
    using System;
    using System.Reflection;
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Linq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Linq() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NET40
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reactive.Strings_Linq", typeof(Strings_Linq).Assembly);
#else
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reactive.Strings_Linq", typeof(Strings_Linq).GetTypeInfo().Assembly);
#endif
          resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot be called when the scheduler is already running. Try using Sleep instead. 的本地化字符串。
        /// </summary>
        internal static string CANT_ADVANCE_WHILE_RUNNING {
            get {
                return ResourceManager.GetString("CANT_ADVANCE_WHILE_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find event &apos;{0}&apos; on object of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string COULD_NOT_FIND_INSTANCE_EVENT {
            get {
                return ResourceManager.GetString("COULD_NOT_FIND_INSTANCE_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find event &apos;{0}&apos; on type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string COULD_NOT_FIND_STATIC_EVENT {
            get {
                return ResourceManager.GetString("COULD_NOT_FIND_STATIC_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add method should take 1 parameter. 的本地化字符串。
        /// </summary>
        internal static string EVENT_ADD_METHOD_SHOULD_TAKE_ONE_PARAMETER {
            get {
                return ResourceManager.GetString("EVENT_ADD_METHOD_SHOULD_TAKE_ONE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The second parameter of the event delegate must be assignable to &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EVENT_ARGS_NOT_ASSIGNABLE {
            get {
                return ResourceManager.GetString("EVENT_ARGS_NOT_ASSIGNABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event is missing the add method. 的本地化字符串。
        /// </summary>
        internal static string EVENT_MISSING_ADD_METHOD {
            get {
                return ResourceManager.GetString("EVENT_MISSING_ADD_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event is missing the remove method. 的本地化字符串。
        /// </summary>
        internal static string EVENT_MISSING_REMOVE_METHOD {
            get {
                return ResourceManager.GetString("EVENT_MISSING_REMOVE_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The event delegate must have a void return type. 的本地化字符串。
        /// </summary>
        internal static string EVENT_MUST_RETURN_VOID {
            get {
                return ResourceManager.GetString("EVENT_MUST_RETURN_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The event delegate must have exactly two parameters. 的本地化字符串。
        /// </summary>
        internal static string EVENT_PATTERN_REQUIRES_TWO_PARAMETERS {
            get {
                return ResourceManager.GetString("EVENT_PATTERN_REQUIRES_TWO_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove method should take 1 parameter. 的本地化字符串。
        /// </summary>
        internal static string EVENT_REMOVE_METHOD_SHOULD_TAKE_ONE_PARAMETER {
            get {
                return ResourceManager.GetString("EVENT_REMOVE_METHOD_SHOULD_TAKE_ONE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The first parameter of the event delegate must be assignable to &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EVENT_SENDER_NOT_ASSIGNABLE {
            get {
                return ResourceManager.GetString("EVENT_SENDER_NOT_ASSIGNABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove method of a WinRT event should take an EventRegistrationToken. 的本地化字符串。
        /// </summary>
        internal static string EVENT_WINRT_REMOVE_METHOD_SHOULD_TAKE_ERT {
            get {
                return ResourceManager.GetString("EVENT_WINRT_REMOVE_METHOD_SHOULD_TAKE_ERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence contains more than one element. 的本地化字符串。
        /// </summary>
        internal static string MORE_THAN_ONE_ELEMENT {
            get {
                return ResourceManager.GetString("MORE_THAN_ONE_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence contains more than one matching element. 的本地化字符串。
        /// </summary>
        internal static string MORE_THAN_ONE_MATCHING_ELEMENT {
            get {
                return ResourceManager.GetString("MORE_THAN_ONE_MATCHING_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence contains no elements. 的本地化字符串。
        /// </summary>
        internal static string NO_ELEMENTS {
            get {
                return ResourceManager.GetString("NO_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence contains no matching element. 的本地化字符串。
        /// </summary>
        internal static string NO_MATCHING_ELEMENTS {
            get {
                return ResourceManager.GetString("NO_MATCHING_ELEMENTS", resourceCulture);
            }
        }
    }
}
